spring:
  profiles:
    active:
      local
  application:
    name: java-WEB-KPI-course

application:
  payment-service:
    base-path: http://localhost:8089
    payments: ${application.payment-service.base-path}/payment-service/v1/payments

  greetings:
    dobby:
      name: dobby
      message: Hello from space cat ${application.greetings.dobby.name}
  feature:
    toggles:
      traveller-greeting: true

---
spring:
  config:
    activate:
      on-profile: dev
application:
  feature:
    toggles:
      traveller-greeting: true
