package org.example.javawebkpicourse.common;

public enum AvailableRoute {

    SECTOR_1_PLANET_ZETA_QUADRANT_121,
    SECTOR_1_PLANET_QUANTUM_QUADRANT_121,
    SECTOR_1_PLANET_DINA_QUADRANT_12,
    SECTOR_2_PLANET_TILDA6_QUADRANT_15,
    SECTOR_2_PLANET_DINA_QUADRANT_15,
    SECTOR_3_PLANET_GARMONIKA64_QUADRANT_3,
    SECTOR_3_PLANET_BETA_QUADRANT_4,
    SECTOR_12_PLANET_DUNA_QUADRANT_8

}
